### ISSUE TITLE
Divide by zero (FPE) error when new correct values are input

### ISSUE THREAD

**Issue by 1to5pc** [senhas-rgb/learning-C#4]
A FPE is triggered when new correct values are input after an attempt at divide by zero is caught by the program
![image](https://github.com/user-attachments/assets/e887a64d-7b50-4e5a-ac26-662f48929585)

**Comment by senhas-rgb** [comment]
Um you fix it. I never encountered it but umm pls provide more information about the problem your facing.

**Comment by 1to5pc** [comment]
After values that cause a divide by 0 error are input, when correct values that can be divided properly are input the program crashes (Ex: 4 & 2)

**Comment by senhas-rgb** [comment]
Fixed partially. No errors provided but the program now only asks for the second number to be entered and cannot divide numbers which results floats.
